version: '3'

services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always
    networks:
      - revproxy-apps

  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - revproxy-apps

  nginx:
    image: nginx:latest
    container_name: nginx
    expose:
      - "80:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    volumes:
      - ./templates:/etc/nginx/templates
    networks:
      - revproxy-apps

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - filebrowser_data:/data
    networks:
      - revproxy-apps

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_PASSWORD: postgres
        PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
        - "5432"
    networks:
        - revproxy-apps
    restart: unless-stopped

  geoserver:
    image: vulhub/geoserver:2.22.1
    volumes:
        - geoserver:/opt/geoserver/data_dir
    ports:
        - "8080"
    networks:
        - revproxy-apps
    restart: on-failure

volumes:
  portainer_data:
  db_data:
  filebrowser_data:
  pgadmin:
  geoserver:
  jupyterlab:

networks:
  revproxy-apps:
    name: revproxy-apps
    external: true
  